name: Reusable workflow

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: HarithaVattikuti/java-test
          ref: main
          token: ${{ secrets.token }}
