name: Cached Temurin 25 Issue
on: [workflow_dispatch]

jobs:
  test-temurin-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04-arm
          - macos-latest
          - macos-13
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Temurin 25 or EA fallback)
        id: setup-java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          check-latest: true
          cache: gradle

      - name: Verify Java
        run: java -version

      # INTENTIONAL mutation for diagnostic reproduction (Linux/Windows Temurin 25)
      - name: Mutate ct.sym for integrity test
        if: contains(steps.setup-java.outputs.version, '25') && runner.os != 'macOS'
        shell: bash
        run: |
          set -e
          CT_SYM="$JAVA_HOME/lib/ct.sym"
          if [ ! -f "$CT_SYM" ]; then
            echo "No ct.sym present; skipping."
            exit 0
          fi
          echo "Original SHA:"
          sha512sum "$CT_SYM"
          TMPDIR=$(mktemp -d)
          pushd "$TMPDIR" > /dev/null
          unzip -qq "$CT_SYM"
          find . -type f -exec touch -t 202401010101 {} \;
          zip -q -X -r rebuilt.sym .
          popd > /dev/null
            cp "$CT_SYM" "${CT_SYM}.bak"
            cp "$TMPDIR/rebuilt.sym" "$CT_SYM"
          echo "Mutated SHA:"
          sha512sum "$CT_SYM"
          rm -rf "$TMPDIR"

      - name: jlink after mutation
        if: contains(steps.setup-java.outputs.version, '25')
        run: |
          set -e
          echo "Running jlink..."
          jlink --add-modules java.base --output minimal-runtime || {
            echo "jlink failed (expected on strict integrity platforms)."
            exit 1
          }
          echo "jlink succeeded (integrity not triggered here)."
