name: Test shell env

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      run: |
        . .github/workflows/tools.sh
        echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV

    - name: Display Java version
      run: echo "Java version is $JAVA_VERSION"
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ env.JAVA_VERSION }}
    # Add other steps here
env:
  JAVA_VERSION: ${{ secrets.JAVA_VERSION }}
